### ISSUE TITLE
It's been crushed by the weight of /r/thebutton?

### ISSUE THREAD

**Issue by QwertzHz** [jamesrom/jamesrom.github.io#7] opened 2015-04-05 23:40 UTC

**Comment by jamesrom** [comment] 2015-04-05 23:43
Duplicate of #6. Thanks for the heads up though :+1:

**Closed** 2015-04-05 23:42 UTC

**Comment by QwertzHz** [comment] 2015-04-05 23:46
Wow, there were only 2 others when I posted it. Must have happened recently.
